// lib/realEstateData.ts

export interface Project {
  id: number;
  slug: string;
  title: string;
  builder: string;
  location: string;
  city: string;
  priceRaw: number;
  price: string;
  bhk: string;
  status: "New Launch" | "Ready To Move" | "Under Construction";
  image: string;
  area: string;
  tag?: string;
  verified: boolean;
  possession?: string;
  propertyType: string;
  totalUnits?: string;
  towers?: string;
  reraNo?: string;
  highlights?: string[];
  views?: string;
  rating?: number;
  lat?: number; // Latitude  (e.g. 28.5046)
  lon?: number; // Longitude (e.g. 77.4050)
}

export interface Property {
  id: number;
  slug: string;
  title: string;
  owner: string;
  ownerType: "Owner" | "Builder" | "Agent";
  location: string;
  society?: string;
  city: string;
  priceRaw: number;
  price: string;
  priceLabel: string;
  bhk: number;
  baths: number;
  status: "Ready To Move" | "Under Construction" | "New";
  listingType: "Sale" | "Rent";
  image: string;
  area: string;
  areaRaw: number;
  floor: string;
  facing: string;
  parking: boolean;
  furnished: "Furnished" | "Semi-Furnished" | "Unfurnished";
  verified: boolean;
  postedDays: number;
  tag?: string;
  highlights: string[];
  views: string;
  rating?: number;
  propertyType:
    | "Apartment"
    | "Villa"
    | "Builder Floor"
    | "Plot"
    | "Penthouse"
    | "Studio";
  lat?: number; // Latitude  (e.g. 28.5046)
  lon?: number; // Longitude (e.g. 77.4050)
}

export interface SearchItem {
  id: string;
  type: "project" | "property";
  name: string;
  location: string;
  city: string;
  price: string;
  slug: string;
  image: string;
  bhk: string | number;
  status: string;
  listingType?: string;
  lat: number;
  lon: number;
}

export const allProjects: Project[] = [
  {
    id: 1,
    slug: "dasnac-jewel-of-noida",
    title: "Dasnac Jewel of Noida",
    builder: "Dasnac",
    location: "Sector 75, Noida",
    city: "Noida",
    priceRaw: 1.89,
    price: "₹1.89 Cr – 12 Cr",
    bhk: "3,4,5 BHK",
    status: "New Launch",
    image: "/property/sobha.webp",
    area: "2200–8500 sq.ft",
    tag: "New",
    verified: true,
    possession: "Dec 2026",
    propertyType: "Apartment",
    totalUnits: "648",
    towers: "6",
    reraNo: "UPRERAPRJ12345",
    highlights: [
      "Golf-facing units",
      "Smart home automation",
      "4-level parking",
    ],
    views: "2.1K",
    rating: 4.8,
  },
  {
    id: 2,
    slug: "godrej-palm-retreat",
    title: "Godrej Palm Retreat",
    builder: "Godrej",
    location: "Sector 150, Noida",
    city: "Noida",
    priceRaw: 1.34,
    price: "₹1.34 Cr – 4.21 Cr",
    bhk: "2,3,4 BHK",
    status: "Ready To Move",
    image: "/property/godrej.jpg",
    area: "1450–3200 sq.ft",
    tag: "Popular",
    verified: true,
    possession: "Ready",
    propertyType: "Apartment",
    totalUnits: "480",
    towers: "4",
    reraNo: "UPRERAPRJ23456",
    highlights: ["Ready possession", "Expressway views", "Godrej quality"],
    views: "3.4K",
    rating: 4.7,
  },
  {
    id: 3,
    slug: "ace-golfshire",
    title: "ACE Golfshire",
    builder: "ACE Group",
    location: "Sector 150, Noida",
    city: "Noida",
    priceRaw: 1.31,
    price: "₹1.31 Cr – 2.3 Cr",
    bhk: "2,3 BHK",
    status: "Ready To Move",
    image: "/property/m3m.webp",
    area: "1200–2100 sq.ft",
    verified: true,
    possession: "Ready",
    propertyType: "Apartment",
    totalUnits: "328",
    towers: "4",
    reraNo: "UPRERAPRJ34567",
    highlights: [
      "Golf course views",
      "Rooftop infinity pool",
      "Zero maintenance",
    ],
    views: "1.8K",
    rating: 4.6,
  },
  {
    id: 4,
    slug: "dasnac-westminster",
    title: "Dasnac Westminster",
    builder: "Dasnac",
    location: "Sector 146, Noida",
    city: "Noida",
    priceRaw: 12,
    price: "₹12 Cr+",
    bhk: "4,5 BHK",
    status: "Under Construction",
    image: "/property/prestige-city-siddharth-vihar.webp",
    area: "5500+ sq.ft",
    tag: "Luxury",
    verified: true,
    possession: "Mar 2027",
    propertyType: "Penthouse",
    totalUnits: "96",
    towers: "2",
    reraNo: "UPRERAPRJ45678",
    highlights: [
      "Ultra-luxury penthouses",
      "Private elevator",
      "24/7 concierge",
    ],
    views: "4.2K",
    rating: 4.9,
  },
  {
    id: 5,
    slug: "m3m-golf-estate",
    title: "M3M Golf Estate",
    builder: "M3M India",
    location: "Sector 65, Gurugram",
    city: "Gurugram",
    priceRaw: 2.5,
    price: "₹2.5 Cr – 6 Cr",
    bhk: "3,4 BHK",
    status: "Under Construction",
    image: "/property/godrej.jpg",
    area: "1800–4200 sq.ft",
    tag: "Premium",
    verified: true,
    possession: "Jun 2027",
    propertyType: "Villa",
    totalUnits: "512",
    towers: "8",
    reraNo: "HRERAGGM12345",
    highlights: [
      "Golf-integrated township",
      "Sky villas",
      "World-class amenities",
    ],
    views: "5.1K",
    rating: 4.8,
  },
  {
    id: 6,
    slug: "sobha-city-gurugram",
    title: "Sobha City",
    builder: "Sobha Realty",
    location: "Sector 108, Gurugram",
    city: "Gurugram",
    priceRaw: 1.8,
    price: "₹1.8 Cr – 4 Cr",
    bhk: "2,3,4 BHK",
    status: "New Launch",
    image: "/property/sobha.webp",
    area: "1350–3000 sq.ft",
    verified: true,
    possession: "Dec 2027",
    propertyType: "Apartment",
    totalUnits: "400",
    towers: "5",
    reraNo: "HRERAGGM23456",
    highlights: ["Sobha quality", "NH-48 connectivity", "IGBC Green certified"],
    views: "2.7K",
    rating: 4.7,
  },
  {
    id: 7,
    slug: "crc-joyous",
    title: "CRC Joyous",
    builder: "CRC Group",
    location: "Noida Extension",
    city: "Greater Noida",
    priceRaw: 1.3,
    price: "₹1.3 Cr – 2.8 Cr",
    bhk: "2,3 BHK",
    status: "Under Construction",
    image: "/property/prestige-city-siddharth-vihar.webp",
    area: "1100–1950 sq.ft",
    verified: true,
    possession: "Sep 2026",
    propertyType: "Apartment",
    totalUnits: "280",
    towers: "3",
    reraNo: "UPRERAPRJ56789",
    highlights: ["Metro nearby", "Low-density living", "EV charging"],
    views: "1.2K",
    rating: 4.4,
  },
  {
    id: 8,
    slug: "ats-knightsbridge",
    title: "ATS Knightsbridge",
    builder: "ATS Infrastructure",
    location: "Sector 124, Noida",
    city: "Noida",
    priceRaw: 4.5,
    price: "₹4.5 Cr – 9 Cr",
    bhk: "4,5 BHK",
    status: "Ready To Move",
    image: "/property/m3m.webp",
    area: "3800–7200 sq.ft",
    tag: "Luxury",
    verified: true,
    possession: "Ready",
    propertyType: "Penthouse",
    totalUnits: "168",
    towers: "3",
    reraNo: "UPRERAPRJ67890",
    highlights: ["Expressway views", "Olympic pool", "Helipad"],
    views: "6.3K",
    rating: 4.9,
  },
  {
    id: 9,
    slug: "gaurs-siddhartham",
    title: "Gaurs Siddhartham",
    builder: "Gaurs Group",
    location: "Siddharth Vihar, Ghzbd",
    city: "Ghaziabad",
    priceRaw: 0.65,
    price: "₹65 L – 1.2 Cr",
    bhk: "2,3 BHK",
    status: "Ready To Move",
    image: "/property/godrej.jpg",
    area: "900–1400 sq.ft",
    tag: "Budget",
    verified: true,
    possession: "Ready",
    propertyType: "Apartment",
    totalUnits: "960",
    towers: "12",
    reraNo: "UPERAGHZ12345",
    highlights: [
      "Ready possession",
      "Affordable pricing",
      "NH-24 connectivity",
    ],
    views: "1.5K",
    rating: 4.3,
  },
  {
    id: 10,
    slug: "nirala-estate",
    title: "Nirala Estate",
    builder: "Nirala World",
    location: "Noida Extension",
    city: "Greater Noida",
    priceRaw: 0.72,
    price: "₹72 L – 1.4 Cr",
    bhk: "2,3 BHK",
    status: "Under Construction",
    image: "/property/sobha.webp",
    area: "950–1600 sq.ft",
    tag: "Budget",
    verified: false,
    possession: "Aug 2026",
    propertyType: "Builder Floor",
    totalUnits: "720",
    towers: "9",
    reraNo: "UPRERAPRJ78901",
    highlights: ["Budget-friendly", "Sports complex", "School within campus"],
    views: "0.9K",
    rating: 4.2,
  },
  {
    id: 11,
    slug: "prestige-primrose-hills",
    title: "Prestige Primrose Hills",
    builder: "Prestige Group",
    location: "Sector 150, Noida",
    city: "Noida",
    priceRaw: 1.9,
    price: "₹1.9 Cr – 3.5 Cr",
    bhk: "3,4 BHK",
    status: "New Launch",
    image: "/property/prestige-city-siddharth-vihar.webp",
    area: "1650–2800 sq.ft",
    verified: true,
    possession: "Jul 2027",
    propertyType: "Apartment",
    totalUnits: "352",
    towers: "4",
    reraNo: "UPRERAPRJ89012",
    highlights: ["Prestige brand", "Expressway frontage", "Landscaped greens"],
    views: "3.8K",
    rating: 4.7,
  },
  {
    id: 12,
    slug: "signature-global-city",
    title: "Signature Global City",
    builder: "Signature Global",
    location: "Sector 37D, Gurugram",
    city: "Gurugram",
    priceRaw: 0.95,
    price: "₹95 L – 1.8 Cr",
    bhk: "2,3 BHK",
    status: "New Launch",
    image: "/property/m3m.webp",
    area: "1050–1750 sq.ft",
    verified: true,
    possession: "Nov 2026",
    propertyType: "Apartment",
    totalUnits: "504",
    towers: "6",
    reraNo: "HRERAGGM34567",
    highlights: ["Affordable Gurugram", "Dwarka Expressway", "DDJAY scheme"],
    views: "2.2K",
    rating: 4.5,
  },

  {
    id: 13,
    slug: "new-project-dadri-greater-noida",
    title: "Aaradhya Greens",
    builder: "Aaradhya Group",
    location: "Sector 3, Greater Noida (Near Dadri)",
    city: "Greater Noida",
    priceRaw: 0.42,
    price: "₹42 L – 85 L",
    bhk: "2,3 BHK",
    status: "New Launch",
    image: "/property/m3m.webp",
    area: "950–1450 sq.ft",
    tag: "New",
    verified: true,
    possession: "Dec 2026",
    propertyType: "Apartment",
    totalUnits: "240",
    towers: "3",
    reraNo: "UPRERAPRJ12349",
    highlights: ["Affordable pricing", "Near metro", "Clubhouse"],
    views: "1.2K",
    rating: 4.3,
    lat: 28.5918, // ✅ Near Dadri
    lon: 77.4345, // ✅ Near Dadri
  },
];

export const allProperties: Property[] = [
  {
    id: 1,
    slug: "3bhk-godrej-palm-retreat-sector150",
    title: "3 BHK in Godrej Palm Retreat",
    owner: "Rajesh Sharma",
    ownerType: "Owner",
    location: "Sector 150, Noida",
    society: "Godrej Palm Retreat",
    city: "Noida",
    priceRaw: 1.85,
    price: "₹1.85 Cr",
    priceLabel: "₹14,230/sqft",
    bhk: 3,
    baths: 3,
    status: "Ready To Move",
    listingType: "Sale",
    image: "/property/godrej.jpg",
    area: "1,300 sq.ft",
    areaRaw: 1300,
    floor: "14th of 25",
    facing: "East",
    parking: true,
    furnished: "Semi-Furnished",
    verified: true,
    postedDays: 2,
    tag: "Owner Direct",
    highlights: ["Corner unit", "Park view", "Modular kitchen"],
    views: "1.2K",
    rating: 4.7,
    propertyType: "Apartment",
    lat: 28.5046,
    lon: 77.405,
  },
  {
    id: 2,
    slug: "4bhk-ace-golfshire-sector150",
    title: "4 BHK in ACE Golfshire",
    owner: "Priya Mehta",
    ownerType: "Owner",
    location: "Sector 150, Noida",
    society: "ACE Golfshire",
    city: "Noida",
    priceRaw: 2.4,
    price: "₹2.4 Cr",
    priceLabel: "₹11,428/sqft",
    bhk: 4,
    baths: 4,
    status: "Ready To Move",
    listingType: "Sale",
    image: "/property/m3m.webp",
    area: "2,100 sq.ft",
    areaRaw: 2100,
    floor: "20th of 22",
    facing: "North-East",
    parking: true,
    furnished: "Furnished",
    verified: true,
    postedDays: 5,
    tag: "Premium",
    highlights: ["Golf course view", "Fully furnished", "Club access"],
    views: "2.8K",
    rating: 4.9,
    propertyType: "Apartment",
    lat: 28.5046,
    lon: 77.405,
  },
  {
    id: 3,
    slug: "2bhk-noida-extension-affordable",
    title: "2 BHK Independent Builder Floor",
    owner: "Sanjay Real Est.",
    ownerType: "Agent",
    location: "Noida Extension",
    society: "",
    city: "Greater Noida",
    priceRaw: 0.52,
    price: "₹52 L",
    priceLabel: "₹4,727/sqft",
    bhk: 2,
    baths: 2,
    status: "Ready To Move",
    listingType: "Sale",
    image: "/property/prestige-city-siddharth-vihar.webp",
    area: "1,100 sq.ft",
    areaRaw: 1100,
    floor: "Ground",
    facing: "West",
    parking: false,
    furnished: "Unfurnished",
    verified: false,
    postedDays: 1,
    tag: "Budget",
    highlights: ["Low price", "Wide road", "Near metro"],
    views: "0.9K",
    rating: 4.1,
    propertyType: "Builder Floor",
    lat: 28.4744,
    lon: 77.504,
  },
  {
    id: 4,
    slug: "5bhk-villa-sector150-noida",
    title: "5 BHK Luxury Villa",
    owner: "Dasnac Homes",
    ownerType: "Builder",
    location: "Sector 128, Noida",
    society: "",
    city: "Noida",
    priceRaw: 8.5,
    price: "₹8.5 Cr",
    priceLabel: "₹17,000/sqft",
    bhk: 5,
    baths: 5,
    status: "Ready To Move",
    listingType: "Sale",
    image: "/property/sobha.webp",
    area: "5,000 sq.ft",
    areaRaw: 5000,
    floor: "G+1",
    facing: "East",
    parking: true,
    furnished: "Furnished",
    verified: true,
    postedDays: 10,
    tag: "Luxury",
    highlights: ["Private pool", "Home theatre", "3-car garage"],
    views: "4.1K",
    rating: 4.9,
    propertyType: "Villa",
    lat: 28.5356,
    lon: 77.3947,
  },
  {
    id: 5,
    slug: "2bhk-rent-sector-62-noida",
    title: "2 BHK for Rent — Sector 62",
    owner: "Amit Verma",
    ownerType: "Owner",
    location: "Sector 62, Noida",
    society: "Mahagun Moderne",
    city: "Noida",
    priceRaw: 0.028,
    price: "₹28,000/mo",
    priceLabel: "₹25/sqft/mo",
    bhk: 2,
    baths: 2,
    status: "Ready To Move",
    listingType: "Rent",
    image: "/property/godrej.jpg",
    area: "1,150 sq.ft",
    areaRaw: 1150,
    floor: "8th of 18",
    facing: "South",
    parking: true,
    furnished: "Semi-Furnished",
    verified: true,
    postedDays: 3,
    highlights: ["Metro nearby", "24×7 security", "Pets allowed"],
    views: "1.8K",
    rating: 4.5,
    propertyType: "Apartment",
    lat: 28.6272,
    lon: 77.3649,
  },
  {
    id: 6,
    slug: "3bhk-rent-gurugram-dlf",
    title: "3 BHK in DLF Phase 4",
    owner: "Neha Singh",
    ownerType: "Owner",
    location: "DLF Phase 4, Gurugram",
    society: "DLF Belaire",
    city: "Gurugram",
    priceRaw: 0.065,
    price: "₹65,000/mo",
    priceLabel: "₹43/sqft/mo",
    bhk: 3,
    baths: 3,
    status: "Ready To Move",
    listingType: "Rent",
    image: "/property/m3m.webp",
    area: "1,500 sq.ft",
    areaRaw: 1500,
    floor: "12th of 30",
    facing: "North",
    parking: true,
    furnished: "Furnished",
    verified: true,
    postedDays: 7,
    tag: "Popular",
    highlights: ["Fully furnished", "Golf course view", "Club paid"],
    views: "3.2K",
    rating: 4.8,
    propertyType: "Apartment",
    lat: 28.4695,
    lon: 77.0856,
  },
  {
    id: 7,
    slug: "plot-yamuna-expressway-200sqyd",
    title: "200 Sq.Yd Plot — YEIDA Scheme",
    owner: "V.K. Builders",
    ownerType: "Builder",
    location: "Sector 22D, Yamuna Exp.",
    society: "",
    city: "Greater Noida",
    priceRaw: 0.95,
    price: "₹95 L",
    priceLabel: "₹4,750/sqft",
    bhk: 0,
    baths: 0,
    status: "New",
    listingType: "Sale",
    image: "/property/prestige-city-siddharth-vihar.webp",
    area: "1,800 sq.ft",
    areaRaw: 1800,
    floor: "Ground",
    facing: "East",
    parking: false,
    furnished: "Unfurnished",
    verified: true,
    postedDays: 4,
    tag: "New",
    highlights: ["YEIDA approved", "Near Jewar airport", "Registry done"],
    views: "2.1K",
    rating: 4.6,
    propertyType: "Plot",
    lat: 28.4089,
    lon: 77.6012,
  },
  {
    id: 8,
    slug: "studio-rent-sector76-noida",
    title: "Studio Apartment for Rent",
    owner: "HomePro Agency",
    ownerType: "Agent",
    location: "Sector 76, Noida",
    society: "Ajnara Homes",
    city: "Noida",
    priceRaw: 0.012,
    price: "₹12,000/mo",
    priceLabel: "₹18/sqft/mo",
    bhk: 1,
    baths: 1,
    status: "Ready To Move",
    listingType: "Rent",
    image: "/property/godrej.jpg",
    area: "650 sq.ft",
    areaRaw: 650,
    floor: "5th of 12",
    facing: "West",
    parking: false,
    furnished: "Furnished",
    verified: false,
    postedDays: 1,
    highlights: ["Metro walkable", "Zero brokerage", "Fully furnished"],
    views: "0.7K",
    rating: 4.2,
    propertyType: "Studio",
    lat: 28.5891,
    lon: 77.3756,
  },
  {
    id: 9,
    slug: "4bhk-penthouse-ats-sector124",
    title: "4 BHK Sky Penthouse — ATS",
    owner: "ATS Realty",
    ownerType: "Builder",
    location: "Sector 124, Noida",
    society: "ATS Knightsbridge",
    city: "Noida",
    priceRaw: 9.0,
    price: "₹9 Cr",
    priceLabel: "₹22,500/sqft",
    bhk: 4,
    baths: 5,
    status: "Ready To Move",
    listingType: "Sale",
    image: "/property/sobha.webp",
    area: "4,000 sq.ft",
    areaRaw: 4000,
    floor: "Top Floor",
    facing: "All sides",
    parking: true,
    furnished: "Furnished",
    verified: true,
    postedDays: 15,
    tag: "Luxury",
    highlights: ["360° view", "Private terrace", "Helipad access"],
    views: "5.2K",
    rating: 5.0,
    propertyType: "Penthouse",
    lat: 28.5356,
    lon: 77.3947,
  },
  {
    id: 10,
    slug: "2bhk-faridabad-affordable-ready",
    title: "2 BHK — Omaxe Heights",
    owner: "Suresh Yadav",
    ownerType: "Owner",
    location: "Sector 86, Faridabad",
    society: "Omaxe Heights",
    city: "Faridabad",
    priceRaw: 0.42,
    price: "₹42 L",
    priceLabel: "₹3,818/sqft",
    bhk: 2,
    baths: 2,
    status: "Ready To Move",
    listingType: "Sale",
    image: "/property/m3m.webp",
    area: "1,100 sq.ft",
    areaRaw: 1100,
    floor: "3rd of 10",
    facing: "South",
    parking: true,
    furnished: "Semi-Furnished",
    verified: true,
    postedDays: 6,
    tag: "Budget",
    highlights: ["Affordable", "Ready to move", "School nearby"],
    views: "1.1K",
    rating: 4.3,
    propertyType: "Apartment",
    lat: 28.42,
    lon: 77.32,
  },
  {
    id: 11,
    slug: "3bhk-rent-indirapuram-ghaziabad",
    title: "3 BHK in Indirapuram",
    owner: "Kavita Mishra",
    ownerType: "Owner",
    location: "Indirapuram, Ghaziabad",
    society: "Shipra Suncity",
    city: "Ghaziabad",
    priceRaw: 0.032,
    price: "₹32,000/mo",
    priceLabel: "₹22/sqft/mo",
    bhk: 3,
    baths: 3,
    status: "Ready To Move",
    listingType: "Rent",
    image: "/property/prestige-city-siddharth-vihar.webp",
    area: "1,450 sq.ft",
    areaRaw: 1450,
    floor: "9th of 14",
    facing: "East",
    parking: true,
    furnished: "Semi-Furnished",
    verified: true,
    postedDays: 2,
    highlights: ["Metro close", "Good society", "Modern kitchen"],
    views: "1.4K",
    rating: 4.4,
    propertyType: "Apartment",
    lat: 28.634,
    lon: 77.385,
  },
  {
    id: 12,
    slug: "villa-rent-gurugram-dlf3",
    title: "4 BHK Independent Villa",
    owner: "Ritu Kapoor",
    ownerType: "Owner",
    location: "DLF Phase 3, Gurugram",
    society: "",
    city: "Gurugram",
    priceRaw: 0.15,
    price: "₹1.5 L/mo",
    priceLabel: "₹75/sqft/mo",
    bhk: 4,
    baths: 4,
    status: "Ready To Move",
    listingType: "Rent",
    image: "/property/sobha.webp",
    area: "2,000 sq.ft",
    areaRaw: 2000,
    floor: "G+1",
    facing: "East",
    parking: true,
    furnished: "Furnished",
    verified: true,
    postedDays: 8,
    tag: "Premium",
    highlights: ["Private garden", "Maid room", "Club membership"],
    views: "2.9K",
    rating: 4.8,
    propertyType: "Villa",
    lat: 28.4695,
    lon: 77.0856,
  },
  {
    id: 13,
    slug: "2bhk-dadri-greater-noida",
    title: "2 BHK Affordable Apartment",
    owner: "Local Developer",
    ownerType: "Builder",
    location: "Dadri, Greater Noida",
    society: "Green Valley Homes",
    city: "Greater Noida",
    priceRaw: 0.38,
    price: "₹38 L",
    priceLabel: "₹3,800/sqft",
    bhk: 2,
    baths: 2,
    status: "Ready To Move",
    listingType: "Sale",
    image: "/property/sobha.webp",
    area: "1,000 sq.ft",
    areaRaw: 1000,
    floor: "3rd of 5",
    facing: "East",
    parking: true,
    furnished: "Semi-Furnished",
    verified: true,
    postedDays: 2,
    tag: "Budget",
    highlights: [
      "Close to Noida-Greater Noida Expressway",
      "Metro connectivity",
      "Schools nearby",
    ],
    views: "1.2K",
    rating: 4.3,
    propertyType: "Apartment",
    lat: 28.5909, // ✅ Near Dadri
    lon: 77.435, // ✅ Near Dadri
  },
  {
    id: 14,
    slug: "3bhk-dadri-greater-noida",
    title: "3 BHK Spacious Apartment",
    owner: "Shree Builders",
    ownerType: "Builder",
    location: "Sector 1, Greater Noida (Near Dadri)",
    society: "Suncity Residency",
    city: "Greater Noida",
    priceRaw: 0.52,
    price: "₹52 L",
    priceLabel: "₹4,200/sqft",
    bhk: 3,
    baths: 3,
    status: "Ready To Move",
    listingType: "Sale",
    image: "/property/m3m.webp",
    area: "1,240 sq.ft",
    areaRaw: 1240,
    floor: "5th of 7",
    facing: "North",
    parking: true,
    furnished: "Unfurnished",
    verified: true,
    postedDays: 5,
    tag: "New",
    highlights: [
      "Walking distance to metro",
      "Gated community",
      "Power backup",
    ],
    views: "0.8K",
    rating: 4.5,
    propertyType: "Apartment",
    lat: 28.5915, // ✅ Near Dadri
    lon: 77.4355, // ✅ Near Dadri
  },
 
];

// Combined search data for autocomplete
export const searchItems = [
  ...allProjects.map((p) => ({
    id: `project-${p.id}`,
    type: "project" as const,
    name: p.title,
    location: p.location,
    city: p.city,
    price: p.price,
    slug: p.slug,
    image: p.image,
    bhk: p.bhk,
    status: p.status,
    lat: p.lat,
    lon: p.lon,
  })),
  ...allProperties.map((prop) => ({
    id: `property-${prop.id}`,
    type: "property" as const,
    name: prop.title,
    location: prop.location,
    city: prop.city,
    price: prop.price,
    slug: prop.slug,
    image: prop.image,
    bhk: prop.bhk,
    status: prop.status,
    listingType: prop.listingType,
    lat: prop.lat,
    lon: prop.lon,
  })),
];
